### ISSUE TITLE
Missing translation for "brightness"

### ISSUE THREAD

**Issue by slamora** [apertium/apertium-eng-spa#20]
First of all, apologies if this is not the proper way to report this kind of issues. I've asked on #apertium channel of IRC and they suggested to report here.

I've found an unkown word on the translation from English to Spanish: [brightness](https://apertium.org/index.eng.html#?dir=eng-spa&q=brightness)

I don't know how can contribute to include "brightness --> brillo" pair translation. Any insight? Thanks!

**Comment by mr-martian** [comment]
The commit above adds "brightness" and has it translate to "brillo" (which was already in the Spanish dictionary).

If you encounter more such issues and want to fix them yourself:

You'll need Apertium installed locally https://wiki.apertium.org/wiki/Installation (probably either Simpleton or "Install Apertium Core by Packaging/Virtual Environment") and then you'll need this repo cloned and compiled (and you might as well go ahead and fork it at this point too).

Pass the two words through the analyzers (on command line for me that's `echo "brightness" | apertium -d . eng-spa-anmor` and for Spanish make it `spa-eng-anmor`). In this case, the output for `brillo` includes `brillo<n><m><sg>`, which is what we want. For English, on the other hand, we get `*brightness`, so we open `apertium-eng-spa.eng.metadix` (file names follow the pattern `repository.language.type`, so this is "English-Spanish translator" - "English-specific" - "dictionary (meta = slightly different from standard format)"). Search the dictionary for some word that is conjugated similarly to `brightness`. It looks like the other `-ness` words are patterned after `access`, so we add an entry in the same format. (If you're not sure where to put it, you can just add it at the end of the `<section>`, which currently ends on line 47097 with "woodcutter".)

To add it to the bilingual dictionary, we need `apertium-eng-spa.eng-spa.dix`. We can copy the entry for any masculine noun and then recompile and get `brightness` translating to `Brillo`. (`brillo` translates to `shine` because it pick the verb reading due to lack of information.)

Once you've checked that your additions work, commit, push, and open a PR.

If you need more detail or get stuck on any of this, someone on the IRC channel will be able to help you.
